                       lorom                                ;      |        |      ;
                                                            ;      |        |      ;
                       incsrc "bank_00.asm"                 ;      |        |      ;
                       incsrc "bank_01.asm"                 ;      |        |      ;
                       incsrc "bank_02.asm"                 ;      |        |      ;
                       incsrc "bank_03.asm"                 ;      |        |      ;
                       incsrc "bank_04.asm"                 ;      |        |      ;
                       incsrc "bank_05.asm"                 ;      |        |      ;
                       incsrc "bank_06.asm"                 ;      |        |      ;
                       incsrc "bank_07.asm"                 ;      |        |      ;
                       incsrc "labels.asm"                  ;      |        |      ;
